### ISSUE TITLE
Setting a timeout in urlopen when used in iokit 

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#262]
Hi,
during the usage of skyfield loader I recognized some timeout errors when loading TLE files from server. When I digged in the reason was a timeout error which occurred when I used the load a second time (? - but why).

As result I have seen that I set the default timeout's in sockets elsewhere, but this influences the urlopen as well. So I checked the default value of the timeout during runtime and saw in a first call it is set to "None", in the second to 0.1 second. So having 0.1s in the second attempt is definitely to short, but "None" during the first might be as well critical, because this means that there is no timeout set resulting in a blocking situation. (see the discussions for example: https://github.com/mesonbuild/meson/issues/4087 in other packages). There the recommendation is to use in all cases the timeout parameter when using the urllib. Setting this parameter in line 479 in iokit.py also solved the problems.

So I have to adjust my overwriting of the default value of the socket timeout parameter for sure, but than the unresolved "None" setting as default might break it anyway.

What do others think about this ?

Michel

**Comment by astrojuanlu** [comment]
@bmerry is trying to add Skyfield to the https://github.com/astropy/coordinates-benchmark matrix in https://github.com/astropy/coordinates-benchmark/pull/60/files, however we keep getting FTP timeouts when downloading the ephemerides from Travis CI:

```
Traceback (most recent call last):
  File "./make.py", line 6, in <module>
    cli()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/astropy/coordinates-benchmark/coordinates_benchmark/commands/benchmark.py", line 70, in benchmark_horizontal
    results = module.convert_horizontal(positions, observers)
  File "/home/travis/build/astropy/coordinates-benchmark/coordinates_benchmark/tools/skyfield.py", line 50, in convert_horizontal
    altaz = _convert_radec_to_altaz(ra, dec, lon, lat, height, time)
  File "/home/travis/build/astropy/coordinates-benchmark/coordinates_benchmark/tools/skyfield.py", line 25, in _convert_radec_to_altaz
    earth = load('de430t.bsp')['earth']
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/skyfield/iokit.py", line 179, in __call__
    path = self._fetch(url, filename, reload, backup)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/skyfield/iokit.py", line 200, in _fetch
    download(url, path, self.verbose, backup=backup)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/skyfield/iokit.py", line 453, in download
    raise e2
OSError: cannot get ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de430t.bsp because <urlopen error ftp error: TimeoutError(110, 'Connection timed out')>
```

I wonder if this is related?

**Comment by brandon-rhodes** [comment]
@astrojuanlu — A `Connection timed out` means that the download was not even able to begin. I would check whether the FTP site is still up, and whether the CI system has firewalls that prevent it from reaching the FTP site.

Alternately, the administrator of the FTP site might have found the volume from Travis's IP address to be unsustainable and could have blocked it from their end to preserve the site as usable for NASA itself and the space flight community. For Skyfield, I keep all the ephemerides that CI needs — or small excerpts from them, for the larger ones — in the repository itself, since I know that government sites can be shut down and disappear if we aren't careful with keeping them sustainable.

@mworion — I am embarrassed to see that I never responded to this back when it was opened in 2019!

First: I am not sure why you saw a timeout of 0.1 when you looked at the socket, as Skyfield does not set any socket timeouts that I am aware of. If you're still watching the issue (and I'll understand completely if you're off on other projects by now!), it would be helpful to see a code sample that shows the 0.1 so I know how to track it down myself. Thanks!

Second: I am not sure Skyfield's downloading logic needs to be much more complicated — indeed, I might have made it too complicated to begin with! I think we should pivot the documentation to recommending some other download engine if Skyfield's simple defaults are not sufficient. The problem is that Python's big popular download library, `requests`, doesn't do FTP. I suppose I should go research the options so the docs can recommend one — or, is that out of scope for the docs, and would inevitably make them out of date sooner than otherwise? Should they just say "go find a good Python download library?" and leave users to find more up-to-date recommendations than the docs themselves might be able to provide?

**Comment by mworion** [comment]
@brandon-rhodes,

no worries about that point. I still enjoying your extraordinary work ! 

First to cleanup the 0.1s story: As skyfield does not set any timeout value at all, it was a remnant of a global setting in my app. So nothing to do !

The only point about the timeout was (and this was due to the fact that there is no chance to set it for skyfield but setting it globally) having skyfield wait long time (forever) when I have a real timeout condition (no exception situation) during timeout. This blocks the application or I have to add code for supervise the download progress of skyfield, which does make the situation not even better. 

Interesting I had an application running with the FTP situation and I don't know why I always worked with requests. At some point in time FTP transfer stopped working (guess it was an undocumented feature and the removed it). So my response to that change was:

```
import urllib.request as ftp

if url.startswith('ftp'):
    with closing(ftp.urlopen(url)) as r:
        with open(filename, 'wb') as f:
            shutil.copyfileobj(r, f)
```

not that nice, but I had to split between FTP and HTTP.
Michel

**Comment by brandon-rhodes** [comment]
> First to cleanup the 0.1s story: As skyfield does not set any timeout value at all, it was a remnant of a global setting in my app. So nothing to do !

Good! I was hoping that setting was from somewhere else :+1: 

> The only point about the timeout was (and this was due to the fact that there is no chance to set it for skyfield but setting it globally) having skyfield wait long time (forever) when I have a real timeout condition (no exception situation) during timeout.

Skyfield uses the Standard Library routine `urlopen()` because it speaks both FTP and HTTP, which does seem to have a `timeout` parameter. I wonder if I should make the Skyfield code more complicated by providing a way to pass that through, or instead update the documentation to show people how to do downloads themselves?

I guess I'll do my usual approach: I'll try to write the docs, and if I realize, "oh, that's a lot to explain!", then I'll make the Skyfield code more complicated instead. :slightly_smiling_face:

**Comment by brandon-rhodes** [comment]
> no worries about that point. I still enjoying your extraordinary work !

(Oh, and, thanks very much for the kinds words!)
