### ISSUE TITLE
numpy.float64 as int deprecation warning

### ISSUE THREAD

**Issue by rtphokie** [skyfielders/python-skyfield#286]
Seeing this warning with Skyfield 1.12

skyfield/almanac.py:76: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
  jd = linspace(jd0, jd1, periods * num // 1.0)

**Comment by brandon-rhodes** [comment]
Thanks for the report! Is there a script I can try running that will show me the error?

**Comment by jaraco** [comment]
Yes.

```
$ cat > ~/draft/repro.py                                                                                                                                    
__requires__ = ['pytz', 'skyfield', 'skyfield-data']

import pytz
from skyfield.api import Loader
from skyfield import almanac
from skyfield_data import get_skyfield_data_path


def calculate_equinoxes(year, timezone='UTC'):
    """ calculate equinox with time zone """
    tz = pytz.timezone(timezone)

    load = Loader(get_skyfield_data_path())
    ts = load.timescale()
    planets = load('de421.bsp')

    t0 = ts.utc(year, 1, 1)
    t1 = ts.utc(year, 12, 31)
    datetimes, _ = almanac.find_discrete(t0, t1, almanac.seasons(planets))
    vernal_equinox = datetimes[0].astimezone(tz).date()
    autumn_equinox = datetimes[2].astimezone(tz).date()
    return vernal_equinox, autumn_equinox


__name__ == '__main__' and calculate_equinoxes(2017)

$ env "PYTHONWARNINGS=error:object of type" pip-run -q -- ~/draft/repro.py                                                                                
Traceback (most recent call last):
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6rlycuwh/numpy/core/function_base.py", line 22, in _index_deprecate
    i = operator.index(i)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaraco/draft/repro.py", line 25, in <module>
    __name__ == '__main__' and calculate_equinoxes(2017)
  File "/Users/jaraco/draft/repro.py", line 19, in calculate_equinoxes
    datetimes, _ = almanac.find_discrete(t0, t1, almanac.seasons(planets))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6rlycuwh/skyfield/almanac.py", line 76, in find_discrete
    jd = linspace(jd0, jd1, periods * num // 1.0)
  File "<__array_function__ internals>", line 5, in linspace
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6rlycuwh/numpy/core/function_base.py", line 128, in linspace
    num = _index_deprecate(num)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6rlycuwh/numpy/core/function_base.py", line 28, in _index_deprecate
    warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

I started seeing this warning in the tests for [calendra](/jaraco/calendra) after the switch from ephem. You can probably distill the issue further, but I'm hoping this is sufficient.

**Comment by brandon-rhodes** [comment]
Thanks for the repro! I just committed a possible fix, but I can't confirm since this exception doesn't happen on my platform. Could you install `master` and see if it's fixed on your end? Thanks!
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```

**Comment by jaraco** [comment]
I was indeed able to confirm the fix  by running 

```
env "PYTHONWARNINGS=error:object of type" pip-run git+https://github.com/skyfielders/python-skyfield -q -- ~/draft/repro.py 
```

It completed without error. I tried it also with the 'latest' skyfield, suggesting the released version has the fix.

To check my sanity, I tested the repro against 1.14 and it failed as before and then with 1.15 and confirm the released version has the fix.

Thanks!

**Comment by brandon-rhodes** [comment]
Thanks for the confirmation! Let me know if you run into any more problems.
