### ISSUE TITLE
Lunar eclipse gives "OutOfRangeError" with a subset bsp

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#531]
I take the ephemeris ```de438.bsp``` and make a small version (from today up to five years from now).  Then I calculate the next lunar eclipse.  Could be wrong here, but I'm sure this worked before the latest update (worked prior to version ```1.35```).

Now I'm getting ```OutOfRangeError```.  See code below and output:

```
#!/usr/bin/env python3


from skyfield import eclipselib
from skyfield.api import load
import datetime, pkg_resources, skyfield, subprocess


def calculateLunarEclipse( ephemeris ):
    utcNow = datetime.datetime.utcnow()
    timeScale = load.timescale( builtin = True )
    now = timeScale.utc( utcNow.year, utcNow.month, utcNow.day, utcNow.hour, utcNow.minute, utcNow.second )
    nowPlusOneYear = timeScale.utc( utcNow.year + 1, utcNow.month, utcNow.day )
    t, y, details = eclipselib.lunar_eclipses( now, nowPlusOneYear, load( ephemeris ) )
    print( ephemeris, t, y, details, '\n' )


def createEphemerisSmall( ephemeris, ephemerisSmall, endYear ):
    today = datetime.date.today()
    future = today.replace( year = endYear )
    dateFormat = "%Y/%m/%d"
    command = "python3 -m jplephem excerpt " + \
              today.strftime( dateFormat ) + " " + \
              future.strftime( dateFormat ) + " " + \
              ephemeris + " " + ephemerisSmall

    print( "Running:", command )

    try:
        subprocess.call( command, shell = True )
        print( "Created", ephemerisSmall, '\n' )

    except subprocess.CalledProcessError as e:
        print( e )


print( "skyfield:", skyfield.__version__, '\n' )
print( "jplephem:", pkg_resources.get_distribution( "jplephem" ).version, '\n' )
ephemeris = "de438.bsp"
endYear = 2025
ephemerisSmall = "de438-" + str( endYear ) + ".bsp"
calculateLunarEclipse( ephemeris )
createEphemerisSmall( ephemeris, ephemerisSmall, endYear )
calculateLunarEclipse( ephemerisSmall )
```

```
skyfield: 1.35 

jplephem: 2.15 

de438.bsp <Time tt=[2459360.97211892 2459537.87782604]> [2 1] {'closest_approach_radians': array([0.068485  , 0.08669159, 0.07967307, 0.05064489, 0.00850881,
       0.03542683, 0.07012251, 0.08672281, 0.08026491, 0.05136474,
       0.00715429, 0.03973237]), 'moon_radius_radians': array([0.0045522 , 0.00468715, 0.00479678, 0.00485767, 0.00485954,
       0.00480487, 0.00470569, 0.00458082, 0.00445362, 0.00434846,
       0.00428593, 0.00427914]), 'penumbra_radius_radians': array([0.02188529, 0.02236287, 0.02273448, 0.02292283, 0.02289893,
       0.02267891, 0.02231094, 0.02186484, 0.02142374, 0.02107088,
       0.02087303, 0.0208691 ]), 'umbra_radius_radians': array([0.01224363, 0.01277468, 0.01322217, 0.01348847, 0.01352574,
       0.01333671, 0.0129631 , 0.01247576, 0.01196634, 0.01153358,
       0.01126451, 0.01121801])} 

Running: python3 -m jplephem excerpt 2021/01/05 2025/01/05 de438.bsp de438-2025.bsp
Created de438-2025.bsp 

Traceback (most recent call last):
  File "lunarEclipse.py", line 44, in <module>
    calculateLunarEclipse( ephemerisSmall )
  File "lunarEclipse.py", line 14, in calculateLunarEclipse
    t, y, details = eclipselib.lunar_eclipses( now, nowPlusOneYear, load( ephemeris ) )
  File "/usr/local/lib/python3.6/dist-packages/skyfield/eclipselib.py", line 71, in lunar_eclipses
    t, y = find_maxima(start_time, end_time, f, num=4)
  File "/usr/local/lib/python3.6/dist-packages/skyfield/searchlib.py", line 139, in find_maxima
    y = f(t)
  File "/usr/local/lib/python3.6/dist-packages/skyfield/eclipselib.py", line 50, in f
    b, velocity = earth_barycenter.compute_and_differentiate(jd, fr)
  File "/usr/local/lib/python3.6/dist-packages/jplephem/spk.py", line 163, in compute_and_differentiate
    return tuple(self.generate(tdb, tdb2))
  File "/usr/local/lib/python3.6/dist-packages/jplephem/spk.py", line 235, in generate
    out_of_range_times=(index < 0) | (index > n),
jplephem.exceptions.OutOfRangeError: segment only covers dates 2459216.5 through 2460688.5
```

Have tried bumping up the end year to 2500 but same error.  Any ideas?

**Comment by brandon-rhodes** [comment]
Good question! The error is happening at the beginning of the range, not the end. I should probably consider documenting this low-level `jplephem` attribute up in the Skyfield docs, that lets you see which times were out of range. You can switch the last line of your script to:
```
try:
    calculateLunarEclipse( ephemerisSmall )
except Exception as e:
    print(e.out_of_range_times)
    raise
```
And you will see that it’s the first time in the range that triggered the problem:
```
[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]
```
The issue is that the routine that looks for a lunar eclipse doesn’t want to miss one right at the beginning of the range you ask about. Your range starts with (as I type this) `A.D. 2021-Jan-05 14:47:21.0000 UTC` — “what,” the routine thinks, “if there’s an eclipse *right then?* I might miss reporting it!”

So it backs up several days before that date as it begins its search for local maxima in the Moon-Sun angle, so that if there's a local maximum right at the start time, it can still catch it.

Where could that be documented better, that might help users understand that they need to be able to predict moon-sun positions a few days before their search start date?

**Comment by Bernmeister** [comment]
Thank you! I have backed up by one month in my script to generate the ephemeris and lunar eclipses are back:

```
def createEphemerisSmall( ephemeris, ephemerisSmall, endYear ):
    from dateutil.relativedelta import relativedelta
    today = datetime.date.today()
    oneMonthPriorToToday = today - relativedelta( months = 1 )
    fiveYearsFromToday = today.replace( year = today.year + 5 )
    dateFormat = "%Y/%m/%d"
    command = "python3 -m jplephem excerpt " + \
        oneMonthPriorToToday.strftime( dateFormat ) + " " + \
        fiveYearsFromToday.strftime( dateFormat ) + " " + \
        ephemeris + " " + ephemerisSmall

    print( "Running:", command )

    try:
        subprocess.call( command, shell = True )
        print( "Created", ephemerisSmall, '\n' )

    except subprocess.CalledProcessError as e:
        print( e )
```

Where to make a note about the ephemeris having extra days (or a month) of padding at the beginning?  A note should be made [here](https://rhodesmill.org/skyfield/planets.html#making-an-excerpt-of-an-ephemeris), mentioning that lunar ecilpses place this condition.  Given that, I'd also put in a note at [here](https://rhodesmill.org/skyfield/almanac.html#lunar-eclipses), adding a bullet point above the first ("Some disagreement is inevitable").  When solar eclipses are implemented (or any other new functionality which have this requirement), I'd add a note to those sections in the documentation too.

**Comment by brandon-rhodes** [comment]
> Where to make a note about the ephemeris having extra days (or a month) of padding at the beginning? …

Thank you for being specific, I'll see about getting explanations added at those places. (Assuming that I don't see any sudden possibility of reworking how maxima are discovered.)

**Comment by Bernmeister** [comment]
I'd add the documentation as it is easiest.  Unfortunately I hit an edge case in which I generated the subset ephemeris and then ran my main application (which amongst other stuff, calls the lunar eclipse module).

Alternatively/additionally, is it possible to improve the error message?  I guess that means you have to check for the start date of the ephemeris first.  Your call!
