### ISSUE TITLE
Failure for ut1 conversion on single Time in the future

### ISSUE THREAD

**Issue by jrs65** [skyfielders/python-skyfield#98]
I'm having a failure trying to convert a single `Time` instance to `ut1` when it is far enough in the future that it needs to use the Morrisson and Stephenson formula for `delta_t`.

```python
>>> from skyfield import api
>>> ts = api.load.timescale()
>>> t = ts.utc(year=2500)
>>> u = t.ut1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bg01/homescinet/k/krs/jrs65/sfdev/python-skyfield/skyfield/timelib.py", line 503, in __getattr__
    self.ut1 = ut1 = self.tt - self.delta_t / DAY_S
  File "/bg01/homescinet/k/krs/jrs65/sfdev/python-skyfield/skyfield/timelib.py", line 508, in __getattr__
    self.delta_t = delta_t = interpolate_delta_t(table, self.tt)
  File "/bg01/homescinet/k/krs/jrs65/sfdev/python-skyfield/skyfield/timelib.py", line 609, in interpolate_delta_t
    delta_t[missing] = delta_t_formula_morrison_and_stephenson_2004(tt)
TypeError: 'float' object does not support item assignment
```

This seems to be a set of slightly subtle interactions, which is a mismatch as it tries to process a scalar input like an array. Below I've copied the problematic function and added a few annotations in comments:

```python

def interpolate_delta_t(delta_t_table, tt):  # tt is a numpy scalar on entry
    """Return interpolated Delta T values for the times in `tt`.

    The 2xN table should provide TT values as element 0 and
    corresponding Delta T values for element 1.  For times outside the
    range of the table, a long-term formula is used instead.

    """
    tt_array, delta_t_array = delta_t_table
    delta_t = interp(tt, tt_array, delta_t_array, nan, nan)  # interp returns a
                                                             # plain Python float

    missing = isnan(delta_t)  # However, isnan returns a numpy scalar bool

    if missing.any():  # Numpy scalars support .any() hence this works

        tt = tt[missing]  # They also support indexing with bools, this 
                          # line essentially turns tt into a length one array

        # Unfortunately here delta_t is still just a float so the indexing fails
        delta_t[missing] = delta_t_formula_morrison_and_stephenson_2004(tt)  
    return delta_t
```

I guess the options are either to find a way getting numpy to implicitly do the right thing here (which I can't think of anything decent), or put in an explicit branch for whether the input is scalar or an array.

**Comment by brandon-rhodes** [comment]
Thank you for providing the fix d2d117855b190a2269e68bcec9d329f51ff24ae5 for this!
